/*
 * Copyright (c) Tile-AI Corporation.
 * Licensed under the MIT License.
 */

/*!
 * \file npu_simt_indirect_load.cc
 * \brief Lower the phase-1 A5 SIMT indirect-load pattern.
 */

#include <tvm/arith/analyzer.h>
#include <tvm/runtime/registry.h>
#include <tvm/tir/expr.h>
#include <tvm/tir/op.h>
#include <tvm/tir/stmt.h>
#include <tvm/tir/stmt_functor.h>
#include <tvm/tir/transform.h>

#include <cstdlib>
#include <iostream>
#include <string>

namespace tvm {
namespace tl {

using namespace tir;

namespace {

constexpr const char *kFeature = "A5 SIMT indirect load phase 1";

enum class IndirectLoadKind {
  kRank1,
  kLutRow2D,
};

struct IndirectLoadPattern {
  const BufferLoadNode *src_load{nullptr};
  const BufferLoadNode *idx_load{nullptr};
  Buffer dst_buffer;
  PrimExpr valid_extent;
  IndirectLoadKind kind{IndirectLoadKind::kRank1};
  PrimExpr src_row;
  PrimExpr idx_row;
  PrimExpr idx_lane_base;
};

bool IsSharedScope(const Buffer &buffer) {
  return buffer.scope() == "shared" || buffer.scope() == "shared.dyn";
}

bool SameExpr(const PrimExpr &lhs, const PrimExpr &rhs) {
  return StructuralEqual()(lhs, rhs);
}

PrimExpr MakeRegion(Buffer buffer, PrimExpr offset, int access_mask,
                    PrimExpr extent) {
  Op region_op = Op::Get("tl.region");
  PrimExpr load = BufferLoad(buffer, {offset});
  Array<PrimExpr> args = {load, make_const(DataType::Int(32), access_mask),
                          extent};
  return Call(DataType::Handle(), region_op, args);
}

PrimExpr MakeRegion2D(Buffer buffer, PrimExpr offset0, PrimExpr offset1,
                      int access_mask, PrimExpr extent0, PrimExpr extent1) {
  Op region_op = Op::Get("tl.region");
  PrimExpr load = BufferLoad(buffer, {offset0, offset1});
  Array<PrimExpr> args = {load, make_const(DataType::Int(32), access_mask),
                          extent0, extent1};
  return Call(DataType::Handle(), region_op, args);
}

bool SimtDebugEnabled() {
  const char *value = std::getenv("TILELANG_SIMT_DUMP_TIR");
  if (value == nullptr) {
    return false;
  }
  std::string normalized(value);
  return !(normalized.empty() || normalized == "0" || normalized == "false" ||
           normalized == "False" || normalized == "FALSE");
}

void DebugDumpStmt(const std::string &label, const Stmt &stmt) {
  if (!SimtDebugEnabled()) {
    return;
  }
  std::cerr << "[NpuSimtIndirectLoad] " << label << ":\n" << stmt << "\n";
}

bool MatchLaneIndex(const PrimExpr &expr, const Var &loop_var, PrimExpr *base) {
  if (SameExpr(expr, loop_var)) {
    *base = make_zero(loop_var.dtype());
    return true;
  }

  const auto *add = expr.as<AddNode>();
  if (!add) {
    return false;
  }
  if (SameExpr(add->a, loop_var)) {
    *base = add->b;
    return true;
  }
  if (SameExpr(add->b, loop_var)) {
    *base = add->a;
    return true;
  }
  return false;
}

PrimExpr MatchTailMask(PrimExpr condition, const Var &loop_var) {
  // Accept the two tail forms generated by TileLang today:
  //   if i < valid
  //   if start + i < N
  // Both lower to a per-block valid lane count consumed by the backend mask.
  const auto *lt = condition.as<LTNode>();
  if (!lt) {
    return PrimExpr();
  }
  if (SameExpr(lt->a, loop_var)) {
    return lt->b;
  }

  const auto *add = lt->a.as<AddNode>();
  if (!add) {
    return PrimExpr();
  }
  if (SameExpr(add->a, loop_var)) {
    return lt->b - add->b;
  }
  if (SameExpr(add->b, loop_var)) {
    return lt->b - add->a;
  }
  return PrimExpr();
}

bool MatchStoreBody(const Stmt &stmt, const Var &loop_var,
                    IndirectLoadPattern *pattern) {
  // Phase 1 deliberately matches only the canonical indirect-load store:
  //   O_UB[i] = X[IDX_UB[i]]
  // Other arithmetic around the result should be expressed in later statements.
  const auto *store = stmt.as<BufferStoreNode>();
  if (!store || store->indices.size() != 1U) {
    return false;
  }
  if (!SameExpr(store->indices[0], loop_var)) {
    return false;
  }

  const auto *src_load = store->value.as<BufferLoadNode>();
  if (!src_load) {
    return false;
  }

  if (src_load->indices.size() == 1U) {
    // 1D pattern: O_UB[i] = X[IDX_UB[i]]
    const auto *idx_load = src_load->indices[0].as<BufferLoadNode>();
    if (!idx_load || idx_load->indices.size() != 1U) {
      return false;
    }
    if (!SameExpr(idx_load->indices[0], loop_var)) {
      return false;
    }

    pattern->src_load = src_load;
    pattern->idx_load = idx_load;
    pattern->dst_buffer = store->buffer;
    pattern->kind = IndirectLoadKind::kRank1;
    return true;
  }

  // 2D LUT-row pattern: O_UB[m] = LUT_SHARED[s, CODES[s, m]]
  if (src_load->indices.size() != 2U) {
    return false;
  }
  const auto *idx_load = src_load->indices[1].as<BufferLoadNode>();
  if (!idx_load || idx_load->indices.size() != 2U) {
    return false;
  }
  if (!SameExpr(src_load->indices[0], idx_load->indices[0])) {
    return false;
  }
  PrimExpr lane_base;
  if (!MatchLaneIndex(idx_load->indices[1], loop_var, &lane_base)) {
    return false;
  }

  pattern->src_load = src_load;
  pattern->idx_load = idx_load;
  pattern->dst_buffer = store->buffer;
  pattern->kind = IndirectLoadKind::kLutRow2D;
  pattern->src_row = src_load->indices[0];
  pattern->idx_row = idx_load->indices[0];
  pattern->idx_lane_base = lane_base;
  return true;
}

class NpuSimtIndirectLoadRewriter : public StmtMutator {
public:
  Stmt VisitStmt_(const ForNode *op) final {
    if (op->kind != ForKind::kParallel) {
      return StmtMutator::VisitStmt_(op);
    }

    DebugDumpStmt("visit T.Parallel", GetRef<For>(op));

    Optional<Stmt> rewritten = TryRewrite(op);
    if (rewritten.defined()) {
      return rewritten.value();
    }
    return StmtMutator::VisitStmt_(op);
  }

private:
  Optional<Stmt> TryRewrite(const ForNode *op) {
    PrimExpr valid_extent = op->extent;
    Stmt body = op->body;

    if (const auto *if_node = op->body.as<IfThenElseNode>()) {
      if (if_node->else_case.defined()) {
        return NullOpt;
      }
      valid_extent = MatchTailMask(if_node->condition, op->loop_var);
      if (!valid_extent.defined()) {
        return NullOpt;
      }
      body = if_node->then_case;
    }

    IndirectLoadPattern pattern;
    if (!MatchStoreBody(body, op->loop_var, &pattern)) {
      return NullOpt;
    }
    pattern.valid_extent = valid_extent;

    if (!CanRewriteBoundary(op, pattern)) {
      return NullOpt;
    }
    Stmt rewritten = BuildIndirectLoad(op, pattern);
    DebugDumpStmt("rewritten TIR", rewritten);
    return rewritten;
  }

  bool CanRewriteBoundary(const ForNode *op,
                          const IndirectLoadPattern &pattern) {
    const auto *extent = op->extent.as<IntImmNode>();
    if (!extent || extent->value <= 0 || !is_zero(op->min)) {
      return false;
    }
    if (!pattern.valid_extent.dtype().is_int() &&
        !pattern.valid_extent.dtype().is_uint()) {
      return false;
    }

    if (pattern.kind == IndirectLoadKind::kRank1) {
      if (pattern.src_load->buffer.scope() != "global") {
        return false;
      }
      if (!IsSharedScope(pattern.idx_load->buffer) ||
          !IsSharedScope(pattern.dst_buffer)) {
        return false;
      }
    } else {
      if (pattern.src_load->buffer.scope() != "global" &&
          !IsSharedScope(pattern.src_load->buffer)) {
        return false;
      }
      if (pattern.idx_load->buffer.scope() != "global" &&
          !IsSharedScope(pattern.idx_load->buffer)) {
        return false;
      }
      if (!IsSharedScope(pattern.dst_buffer)) {
        return false;
      }
    }

    if (pattern.src_load->buffer->dtype != DataType::Float(32)) {
      return false;
    }
    if (pattern.idx_load->buffer->dtype != DataType::Int(32)) {
      return false;
    }
    return pattern.dst_buffer->dtype == pattern.src_load->buffer->dtype;
  }

  Stmt BuildIndirectLoad(const ForNode *op,
                         const IndirectLoadPattern &pattern) {
    PrimExpr zero = make_zero(op->loop_var.dtype());
    PrimExpr block = op->extent;

    PrimExpr src_region;
    PrimExpr idx_region;
    if (pattern.kind == IndirectLoadKind::kRank1) {
      src_region = MakeRegion(pattern.src_load->buffer, zero, 1,
                              make_const(DataType::Int(32), 1));
      idx_region = MakeRegion(pattern.idx_load->buffer, zero, 1, block);
    } else {
      src_region = MakeRegion2D(pattern.src_load->buffer, pattern.src_row, zero,
                                1, make_const(DataType::Int(32), 1),
                                pattern.src_load->buffer->shape[1]);
      idx_region = MakeRegion2D(pattern.idx_load->buffer, pattern.idx_row,
                                pattern.idx_lane_base, 1,
                                make_const(DataType::Int(32), 1), block);
    }
    PrimExpr dst_region = MakeRegion(pattern.dst_buffer, zero, 2, block);

    Op indirect_load_op = Op::Get("tl.npuir_indirect_load");
    Array<PrimExpr> args = {src_region, idx_region, dst_region,
                            pattern.valid_extent};
    PrimExpr call = Call(DataType::Void(), indirect_load_op, args);
    return Evaluate(call);
  }
};

} // namespace

using namespace tir::transform;

tvm::transform::Pass NpuSimtIndirectLoad() {
  auto pass_func = [=](PrimFunc f, IRModule m, PassContext ctx) {
    // This pass must run before NpuLoopVectorize, otherwise the canonical
    // T.Parallel form is already converted into the SIMD loop representation.
    auto *new_pf = f.CopyOnWrite();
    new_pf->body = NpuSimtIndirectLoadRewriter()(std::move(new_pf->body));
    return f;
  };
  return CreatePrimFuncPass(pass_func, 0, "tl.NpuSimtIndirectLoad", {});
}

TVM_REGISTER_GLOBAL("tl.transform.NpuSimtIndirectLoad")
    .set_body_typed(NpuSimtIndirectLoad);

} // namespace tl
} // namespace tvm
